### ISSUE TITLE
how to configuation storm ui with storm cluster on docker ? 

### ISSUE THREAD

**Issue by silence-liu** [31z4/storm-docker#11]
hi~
I used official repositpry storm docker image and docker-compose build a storm cluster.
but used storm ui，I can't visit every nodes log，because all log visit port is 8000，but only one port can mapping on host computer。 so how to configuation storm ui with storm cluster on docker ？ please give me some suggestion， thank you ！

**Comment by 31z4** [comment]
There is a known [issue](https://issues.apache.org/jira/browse/STORM-1342) with `logviewer` in dockerized environment. One possible solution is described [here](https://github.com/31z4/storm-docker/issues/3).

**Comment by silence-liu** [comment]
give every container a Ip adress used pipework is my solution.  but pipework is not stable，Each time the container restarts need to reset ip，thankyou very much for  your Suggestion。
