### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by mr-cloud** [31z4/storm-docker#13]
I followed the procedure listed on the Docker hub for Storm 1.2.1 to set up a minimum Storm cluster. But when I executed the command to submit a topology as the documentation suggests `$ docker run --link some-nimbus:nimbus -it --rm -v $(pwd)/topology.jar:/topology.jar storm storm jar /topology.jar org.apache.storm.starter.WordCountTopology topology`. The error occurred in the console:

> Error: Could not find or load main class org.apache.storm.starter.ExclamationTopology. 

The jar file is compiled from the official master branch with version 1.2.1. I confirmed that the jar file in local current directory does include the org.apache.storm.starter.ExclamationTopology class with the correct path.

**Comment by mr-cloud** [comment]
Finally, I got it. The official docker image on Docker Hub for Storm 1.2.1 misses the class called `ConfigurableTopology`.

**Comment by 31z4** [comment]
Hello @mr-cloud Any suggestions how to fix that?

**Comment by mr-cloud** [comment]
@31z4 Two methods you can try: one is compiling class `ConfigurableTopology` separately and patch it into your topology jar file with right path. The second is compiling your topology jar with storm-client dependency at `compile` scope. Then you should kick out `defaults.yaml` within the jar file root directory so that Storm would not complain about the duplicated `defaults.yaml` files and abort.

**Comment by mr-cloud** [comment]
This kind of issue still exists. I build another plain maven project and pom file is shown as last. I try to run the examples from `storm-starter` project. Here I copied `LambdaTopology` into my project. when I submit the topology assigning  `LambdaTopology` as the main class. Error occurs:
> Running: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apache-storm-1.2.1 -Dstorm.log.dir=/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /apache-storm-1.2.1/*:/apache-storm-1.2.1/lib/*:/apache-storm-1.2.1/extlib/*:/storm-examples-1.0-SNAPSHOT-jar-with-dependencies.jar:/conf:/apache-storm-1.2.1/bin -Dstorm.jar=/storm-examples-1.0-SNAPSHOT-jar-with-dependencies.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} uni.mlgb.storm.examples.LambdaTopology lambda
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/storm/lambda/SerializableSupplier
        at uni.mlgb.storm.examples.LambdaTopology.run(LambdaTopology.java:48)
        at uni.mlgb.storm.examples.ConfigurableTopology.start(ConfigurableTopology.java:68)
        at uni.mlgb.storm.examples.LambdaTopology.main(LambdaTopology.java:29)
Caused by: java.lang.NoClassDefFoundError: org/apache/storm/lambda/SerializableSupplier
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.apache.storm.lambda.SerializableSupplier
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more

I found that the `storm-core-1.2.1.jar` in the docker image missing all classes under `lambda` directory, e.g.,  `SerializableSupplier`. So I changed the scope  `storm-core` dependency  to `compile`. After compiled again, I validated that `SerializableSupplier` exsisted in the jar file now. But when sumbitted topology, I got another error:
> SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/apache-storm-1.2.1/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/lambda.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Running: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apache-storm-1.2.1 -Dstorm.log.dir=/logs -Djav
a.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /apache-storm-1.2.1/*:/apache-storm-1.2.1/lib/*:/apache-storm-1.2.1/extlib/
*:/lambda.jar:/conf:/apache-storm-1.2.1/bin -Dstorm.jar=/lambda.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} uni.mlgb.storm.examples.Lam
bdaTopology lambda
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.storm.topology.TopologyBuilder.setSpout(Ljava/lang/String;Lorg/apache/storm/lambda/Se
rializableSupplier;)Lorg/apache/storm/topology/SpoutDeclarer;
        at uni.mlgb.storm.examples.LambdaTopology.run(LambdaTopology.java:48)
        at uni.mlgb.storm.examples.ConfigurableTopology.start(ConfigurableTopology.java:68)
        at uni.mlgb.storm.examples.LambdaTopology.main(LambdaTopology.java:29)

This bug really confused me. How can I solve it?

My pom file as below,

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>uni.mlgb</groupId>
    <artifactId>storm-examples</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.apache.storm</groupId>
            <artifactId>storm-core</artifactId>
            <version>2.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.8.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass></mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by 31z4** [comment]
@mr-cloud, sorry for the delayed respone. As far as I understand the issue is not related to the Docker image itself, right? Because the image uses a Storm distribution [as is](https://github.com/31z4/storm-docker/blob/master/1.2.1/Dockerfile#L27-L34). Please report the issue [upstream](https://issues.apache.org/jira/projects/STORM/issues) if so. Thanks!

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
