### ISSUE TITLE
Question about storm.yaml configuration

### ISSUE THREAD

**Issue by fedelemantuano** [31z4/storm-docker#15]
### Expected behavior
This is only a question.

### Actual behavior
Can you explain me why the configuration storm.yaml in /conf works, if the installation is in other path?

### System configuration

**Comment by 31z4** [comment]
Hello @fedelemantuano. Are you asking how do we force Storm to read its configuration from `/conf`? If that's the question then we just set the [`STOM_CONF_DIR`](https://github.com/31z4/storm-docker/blob/master/1.2.1/Dockerfile#L10) environment variable to `/conf` by default. Storm uses this variable to locate its config.

**Comment by fedelemantuano** [comment]
@31z4 thanks a lot. I have another question. Is there an official page where I can read all environment variables about Apache Storm?

**Comment by 31z4** [comment]
@fedelemantuano I don't think there is a dedicated documentation on the supported environment variables. But you may refer to [storm](https://github.com/apache/storm/blob/1.1.x-branch/bin/storm) and [storm.py](https://github.com/apache/storm/blob/1.1.x-branch/bin/storm.py).

**Comment by fedelemantuano** [comment]
Hi @31z4 thanks a lot for support.
