### ISSUE TITLE
Set the time zone inside the container.

### ISSUE THREAD

**Issue by gurpreet-flipkart** [31z4/storm-docker#17]
How to configure the timezone inside the Storm container? Currently the default timezone is UTC. 
Do I have to extend the image and set the timezone using tzdata?

something like:
RUN echo "Asia/Kolkata" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

Please suggest.

**Comment by 31z4** [comment]
The image is based on Alpine Linux. So please follow [this guide](https://wiki.alpinelinux.org/wiki/Setting_the_timezone).
