### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [31z4/storm-docker#19]
Hi,

The Storm docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: 
```
Stable: latest: 1.2.2
```

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by odidev** [comment]
Any update for this?
Do let me know, if some kind of PR is required for this

**Comment by odidev** [comment]
PR : [raised here](https://github.com/docker-library/official-images/pull/4607).

Please have a look and provide your guidance.

Regards,

**Comment by tianon** [comment]
@31z4 is this something you're willing to support?

**Comment by 31z4** [comment]
Hello @odidev @tianon and sorry for the delay. Adding multiarch support is a great idea 👍 But before doing this I'd love to have at least a single basic test within https://github.com/docker-library/official-images so that we can always see that a container starts for a certain architecture. You can check https://github.com/docker-library/official-images/pull/3672 as a reference. The test could be something like starting `nimbus` and checking that its TCP port is open or checking for a certain line in logs.

Is this something feasible for you @odidev?

**Comment by odidev** [comment]
@31z4: Thanks for taking out some time for this too.
I will surely try to run Storm with ```Nimbus``` on my system and capture some logs.

**Comment by 31z4** [comment]
Awesome! I mean adding a simple automated test like [this](https://github.com/docker-library/official-images/pull/3672/files#diff-3685be751057ae70424eb9beb378b014) would help maintain the image functioning on multiple architectures.

**Comment by tianon** [comment]
(Just to be clear, we don't run those tests on _every_ built image before pushing for a number of reasons such as increased load, increased publish delay, flaky tests, etc, but we do run them on any image update PR as a basic smoke test.  I wouldn't recommend relying on them alone to detect multiarch issues unless you're actively running them separate from our processes.  It's also fair to simply rely on users to report multiarch issues.)

**Comment by 31z4** [comment]
Thanks for the clarification @tianon. A basic smoke test is exactly what I'd love to see since I don't have a chance to run Storm on any arch except `amd64`.

If we decide to go without tests and enable mutiarch for Storm is there any recommended flow or past experience of solving archtecture specific issues for images?

**Comment by tianon** [comment]
I can perform a basic smoke test on any arch, and if you request it I'm
happy to do so on any PR before publishing.

I'm also happy to do some amount of additional debugging/digging on our
infrastructure if something isn't working right to help narrow it down.
Unfortunately for much beyond that you'll need to acquire or emulate your
own system (or drop support for the architecture later if you can't figure
it out and/or can't get upstream interested in helping figure it out).

**Comment by odidev** [comment]
Hi Guys,
Any update regarding ```storm``` support for ```arm64v8```

If required then,
```
Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/
```

**Comment by odidev** [comment]
Can we raise a PR for this now?
The earlier PR https://github.com/docker-library/official-images/pull/4607 was closed because of ongoing discussion.

@tianon - What do you say?

Regards,

**Comment by 31z4** [comment]
Hey @odidev, apologies for the delayed response here 🙏 I've finally decided to give it a try: https://github.com/docker-library/official-images/pull/4824

**Comment by odidev** [comment]
Hi @31z4,

It's great that you finally decided to give it a try over ```arm64v8```.
Do let me know, if you face any hurdle and need an assistance.

I hope to see ```storm``` running officially over arm64 systems very soon.

Regards,

**Comment by 31z4** [comment]
Done.
