### ISSUE TITLE
How to set Leader Host Name

### ISSUE THREAD

**Issue by wurangbo** [31z4/storm-docker#22]
hi,
  when I submitted a topology to nimbus remotely using nimbusclient, I got
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: 6529caa5230d

ps 6529caa5230d is the docker container Id, I want to know how to set it,

**Comment by 31z4** [comment]
`--hostname` flag for the `docker run` could be used for that.

**Comment by wurangbo** [comment]
hi @31z4 ,
   I want to run it as an env varibale using docker compose, could you tell me how to set it?

**Comment by 31z4** [comment]
Same option is [available](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) for Docker Compose. Closing this now as unrelated to the image. Please refer to Docker documentation.
