### ISSUE TITLE
Version bumps?

### ISSUE THREAD

**Issue by tianon** [31z4/storm-docker#34]
Hey @31z4!  I think we're probably due for a version bump?  It looks like Storm upstream released 2.3.1 and 2.2.2. (Interestingly, no 1.x -- is that still an actively supported release line?)

I believe both of those include log4j version bumps, so maybe important? :see_no_evil:

**Comment by 31z4** [comment]
Hi @tianon. Thanks for the update! I wonder how did you know that? Neither news nor [downloads](https://storm.apache.org/downloads.html) on the official site show these updates 🤔

**Comment by tianon** [comment]
I found them under tags in Git: https://github.com/apache/storm/tags 😅

(While looking for whether they had a release with the log4j bump for log4shell mitigations 🙈)

**Comment by 31z4** [comment]
I tried to build an image for `2.3.1` locally but it looks like the distro is not uploaded to Apache mirrors yet. None of the following succeeds:
```
#7 0.158 + wget -q -O apache-storm-2.3.1.tar.gz https://www.apache.org/dyn/closer.cgi?action=download&filename=storm/apache-storm-2.3.1/apache-storm-2.3.1.tar.gz
#7 0.681 + wget -q -O apache-storm-2.3.1.tar.gz https://www-us.apache.org/dist/storm/apache-storm-2.3.1/apache-storm-2.3.1.tar.gz
#7 0.874 + wget -q -O apache-storm-2.3.1.tar.gz https://www.apache.org/dist/storm/apache-storm-2.3.1/apache-storm-2.3.1.tar.gz
#7 1.647 + wget -q -O apache-storm-2.3.1.tar.gz https://archive.apache.org/dist/storm/apache-storm-2.3.1/apache-storm-2.3.1.tar.gz
```
So I guess we'll have to wait until it's there.

**Comment by mariannovotny** [comment]
Hi @31z4,
Storm 2.4.0 has been released https://storm.apache.org/2022/03/25/storm240-released.html with important security updates in dependencies (eg log4j) Can you please upgrade versions?
