### ISSUE TITLE
Can't find relative docker image for the new Mac (M2 chips)

### ISSUE THREAD

**Issue by langrui** [31z4/storm-docker#38]
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by 31z4** [comment]
`arm64v8` support will be added once [this PR](https://github.com/docker-library/official-images/pull/14040) is merged.

**Comment by 31z4** [comment]
Added `arm64v8` to `temurin` based tags. `1.2.4` and `2.4.0` are no longer maintained because these tags were based on [completely deprecated](https://github.com/docker-library/openjdk#deprecated) `openjdk` image.
