### ISSUE TITLE
Supervisor still failing in storm:2.4.0-temurin because of unrecognized Java 11 VM option

### ISSUE THREAD

**Issue by raulnegrean** [31z4/storm-docker#39]
This issue follows up on [#32](https://github.com/31z4/storm-docker/issues/32). PR [#3504](https://github.com/apache/storm/pull/3503) fixes the bug, but, from what I'm seeing, a patch has yet to be released. Therefore, the supervisor process is still failing in the [latest](https://hub.docker.com/layers/library/storm/2.4.0-temurin/images/sha256-cb155939c9e613a66ba45519c6dec7cb932c9cdaa7182ce96e7dfdfb03623064?context=explore) image build.

### Expected behavior
Supervisor ignores unrecognized Java 11 VM options.

### Actual behavior
Supervisor fails because of deprecated VM options.

```text
2023-02-26 12:11:52.741 STDERR Thread-0 [INFO] Unrecognized VM option 'PrintGCDateStamps'
2023-02-26 12:11:52.741 STDERR Thread-1 [INFO] [0.000s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:artifacts/gc.log instead.
2023-02-26 12:11:52.743 STDERR Thread-0 [INFO] Error: Could not create the Java Virtual Machine.
2023-02-26 12:11:52.743 STDERR Thread-0 [INFO] Error: A fatal exception has occurred. Program will exit.
```

However, adding the `IgnoreUnrecognizedVMOptions` option in `/conf/storm.yaml` to override the default `worker.childopts` config fixes the issue:
```yaml
worker.childopts: "-Xmx%HEAP-MEM%m -XX:+IgnoreUnrecognizedVMOptions -XX:+PrintGCDetails -Xloggc:artifacts/gc.log -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"
```
Are you guys planning to release a patch soon?

**Comment by 31z4** [comment]
Adding a workaround seems like a good idea. At least until the patched version is released by the upstream.

I was going to patch `conf/defaults.yaml` similarly to [STORM-3886](https://github.com/apache/storm/pull/3503). But there's no such file in the distribution for some reason.

```console
$ docker run -it --rm storm:2.4.0-temurin sh -c 'pwd; ls conf'
Unable to find image 'storm:2.4.0-temurin' locally
2.4.0-temurin: Pulling from library/storm
Digest: sha256:d91fa2e8254f22ddbf0b477f228c690f392fe8d359a6be3b9f9094fb54f6b16c
Status: Downloaded newer image for storm:2.4.0-temurin
/apache-storm-2.4.0
seccomp.json.example  storm_env.ini  storm-env.ps1  storm-env.sh  storm.yaml
```

Although, this file exists in the source distribution [apache-storm-2.4.0-src.tar.gz](https://dlcdn.apache.org/storm/apache-storm-2.4.0/apache-storm-2.4.0-src.tar.gz). But the Docker image uses [apache-storm-2.4.0.tar.gz](https://dlcdn.apache.org/storm/apache-storm-2.4.0/apache-storm-2.4.0.tar.gz).

So I'd doubt that changes in `conf/defaults.yaml` have the desired effect. We need to try to figure this out with the upstream maintainers.

As an alternative solution it's possible to include fixed `worker.childopts` to the default `storm.yaml` that is generated by [`docker-entrypoint.sh`](https://github.com/31z4/storm-docker/blob/14c749848c8ff7c955f2b29c57e327ae80fbbb7e/2.4.0/docker-entrypoint.sh). But it will only work for the cases when users don't provide custom config.

**Comment by 31z4** [comment]
I tried to put `defaults.yaml` to `$STORM_CONF_DIR` but got the following error during startup:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.storm.command.ConfigValue.main(ConfigValue.java:38)
Caused by: java.lang.RuntimeException: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/apache-storm-2.4.0/lib/storm-client-2.4.0.jar!/defaults.yaml, file:/conf/defaults.yaml]
	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:198)
	at org.apache.storm.utils.Utils.readDefaultConfig(Utils.java:241)
	at org.apache.storm.utils.Utils.readStormConfig(Utils.java:304)
	at org.apache.storm.utils.Utils.<clinit>(Utils.java:132)
	... 1 more
Caused by: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/apache-storm-2.4.0/lib/storm-client-2.4.0.jar!/defaults.yaml, file:/conf/defaults.yaml]
	at org.apache.storm.utils.Utils.getConfigFileInputStream(Utils.java:228)
	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:176)
	... 4 more
```

So it looks like `defaults.yaml` gets packed into JARs during distribution phase and changes in its source should have the desired effect.

It seems that the only feasible option now is to include the workaround to the auto-generated `storm.yaml` (see https://github.com/31z4/storm-docker/pull/40) and wait until upstream releases a distribution with the proper fix.

What do you think @raulnegrean? Maybe I'm missing some better ways to address the issue?

**Comment by raulnegrean** [comment]
Thanks for addressing this, @31z4.

> What do you think @raulnegrean? Maybe I'm missing some better ways to address the issue?

Indeed, from what I'm seeing, the `defaults.yaml` is packaged in the storm-client JAR (see [here](https://github.com/apache/storm/blob/2.4.x-branch/storm-client/pom.xml#L126)), so we could directly patch the JAR to avoid having this issue if users provide their own `storm.yaml` (see details in PR https://github.com/31z4/storm-docker/compare/master...raulnegrean:storm-docker:patch-1). 

Definitely less orthodox than what you're proposing, but, assuming I'm not missing something, this could fix the problem until a patch is released.

**Comment by 31z4** [comment]
Thanks for the suggestion @raulnegrean 🙏 

I made a PR inspired by your patch https://github.com/31z4/storm-docker/pull/41. It's just a single `RUN` instruction. So it will be easy to remove once not needed.

I'm happy to merge after your review ☺️

**Comment by raulnegrean** [comment]
Looks good! Thanks for fixing this, @31z4.

**Comment by melekabbassi** [comment]
> Thanks for addressing this, @31z4.
> 
> > What do you think @raulnegrean? Maybe I'm missing some better ways to address the issue?
> 
> Indeed, from what I'm seeing, the `defaults.yaml` is packaged in the storm-client JAR (see [here](https://github.com/apache/storm/blob/2.4.x-branch/storm-client/pom.xml#L126)), so we could directly patch the JAR to avoid having this issue if users provide their own `storm.yaml` (see details in PR [master...raulnegrean:storm-docker:patch-1](https://github.com/31z4/storm-docker/compare/master...raulnegrean:storm-docker:patch-1)).
> 
> Definitely less orthodox than what you're proposing, but, assuming I'm not missing something, this could fix the problem until a patch is released.

this was really helpful, Thank you!
